### ISSUE TITLE
Setup Instructions

### ISSUE THREAD

**Issue by dufferzafar** [rljacobson/Guru#2]
I wanted to get the project running, so I first ran `make` and the ui files got built successfully.

I then ran `python Guru.py` but got the following error

```
Traceback (most recent call last):
  File "Guru.py", line 3, in <module>
    from guru.globals import startServerThread, cleanup
  File "/home/dufferzafar/dev/clones/Guru/guru/globals.py", line 19, in <module>
    import sagenb.misc.misc
ImportError: No module named sagenb.misc.misc
```

I figured the error was due to missing [site-packages](https://github.com/rljacobson/Guru/blob/master/guru/globals.py#L14). So I changed that line to:

``` python
import site
site.addsitedir("/home/dufferzafar/dev/sage-6.4.1/local/lib/python2.7/site-packages")
```

As I have sage built from sources in this directory: 
`/home/dufferzafar/dev/sage-6.4.1`

Again running `python Guru.py` gives: 

```
Traceback (most recent call last):
  File "Guru.py", line 3, in <module>
    from guru.globals import startServerThread, cleanup
  File "/home/dufferzafar/dev/clones/Guru/guru/globals.py", line 32, in <module>
    from sagenb.notebook.notebook import Notebook
  File "/home/dufferzafar/dev/sage-6.4.1/local/lib/python2.7/site-packages/sagenb-0.11.1-py2.7.egg/sagenb/notebook/notebook.py", line 39, in <module>
    from . import css          # style
  File "/home/dufferzafar/dev/sage-6.4.1/local/lib/python2.7/site-packages/sagenb-0.11.1-py2.7.egg/sagenb/notebook/css.py", line 17, in <module>
    from sagenb.notebook.template import template
  File "/home/dufferzafar/dev/sage-6.4.1/local/lib/python2.7/site-packages/sagenb-0.11.1-py2.7.egg/sagenb/notebook/template.py", line 23, in <module>
    from sagenb.notebook.cell import number_of_rows
  File "/home/dufferzafar/dev/sage-6.4.1/local/lib/python2.7/site-packages/sagenb-0.11.1-py2.7.egg/sagenb/notebook/cell.py", line 26, in <module>
    from interact import (INTERACT_RESTART, INTERACT_UPDATE_PREFIX,
  File "/home/dufferzafar/dev/sage-6.4.1/local/lib/python2.7/site-packages/sagenb-0.11.1-py2.7.egg/sagenb/notebook/interact.py", line 157, in <module>
    from sage.misc.cachefunc import cached_method
ImportError: libcsage.so: cannot open shared object file: No such file or directory
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/dufferzafar/dev/sage-6.4.1/local/lib/python2.7/site-packages/sage/misc/temporary_file.py", line 51, in delete_tmpfiles
    from sage.misc.misc import SAGE_TMP
  File "/home/dufferzafar/dev/sage-6.4.1/local/lib/python2.7/site-packages/sage/misc/misc.py", line 47, in <module>
    import sage.misc.prandom as random
  File "/home/dufferzafar/dev/sage-6.4.1/local/lib/python2.7/site-packages/sage/misc/prandom.py", line 58, in <module>
    from sage.misc.randstate import current_randstate
ImportError: libcsage.so: cannot open shared object file: No such file or directory
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/dufferzafar/dev/sage-6.4.1/local/lib/python2.7/site-packages/sage/misc/temporary_file.py", line 51, in delete_tmpfiles
    from sage.misc.misc import SAGE_TMP
  File "/home/dufferzafar/dev/sage-6.4.1/local/lib/python2.7/site-packages/sage/misc/misc.py", line 47, in <module>
    import sage.misc.prandom as random
  File "/home/dufferzafar/dev/sage-6.4.1/local/lib/python2.7/site-packages/sage/misc/prandom.py", line 58, in <module>
    from sage.misc.randstate import current_randstate
ImportError: libcsage.so: cannot open shared object file: No such file or directory
```

Now I can't figure out the reason of this error. I've tried adding this, but nothing changed.

``` python
sys.path.append("/home/dufferzafar/dev/sage-6.4.1/local/lib")
```

Could you please provide some setup instructions?

**Comment by rljacobson** [comment]
Guru uses a version of the notebook code from Sage that has been modified to not depend on the rest of Sage. When you added your Sage site-packages directory to the path, you essentially pointed Guru to an unmodified version of the notebook code, and that's what's causing your problem. 

To get a working app, what you really want is the Guru-NB project, https://github.com/rljacobson/Guru-NB. It _should_ have all it's dependencies included (though honestly it might not). You shouldn't need to monkey with the site-packages. Just cd to the Guru-NB directory and run `python Guru.py`. When you create your first worksheet, it should prompt you to identify the location of your Sage installation. Be patient when executing your first command on your first notebook, as it takes a bit of time for Sage to start.

You're welcome to hack away at this project, but I have actually suspended my own work on Guru after conversations with Sage/SageMathCloud's lead developer. The SageMathCloud (SMC) notebook interface was recently open-sourced, and I think it makes much more sense to use SMC as a basis for a standalone notebook interface than it does to use the old Sage Notebook as Guru currently does.

**Comment by dufferzafar** [comment]
Two packages namely `Jinja2` and `markupsafe` were missing from the site-packages directory. I added those and ran Guru but got this :/

```
[1]    5650 segmentation fault (core dumped)  python Guru.py
```

**Comment by rljacobson** [comment]
Sorry for the delayed response.

That is an unfortunate failure. Doesn't give us much to go on. My guess at this point is that there's a problem with your pyside installation. I am not sure how to advise you at this point. If you figure out the problem, please come back and let me know.
